@base_url = http://localhost:3000/auth
@user_base_url = http://localhost:3000/user
@profile_base_url = http://localhost:3000/profile
@expenses_base_url = http://localhost:3000/expenses
@recipes_base_url = http://localhost:3000/recipes
@ingredients_base_url = http://localhost:3000/ingredients
@authToken = {{signIn.response.body.access_token}}


# @name updating
PATCH  {{expenses_base_url}}
Content-Type: application/json

{
  "valuePartial": 21,
  "serving": 5,
  "pack": 3,
  "profit": 70,
  "recipeId": 43
}
###

# @name get
GET  {{expenses_base_url}}/43
Content-Type: application/json

###

# @name signIn
POST {{base_url}}/signin
Content-Type: application/json

{
  "email": "teste10@gmail.com",
  "password": "Password123@"
}

###

# @name signOut
POST {{base_url}}/signout
Content-Type: application/json

###

# @name register
POST {{base_url}}/register
Content-Type: application/json

{
  "name": "teste5",
  "email": "teste10@gmail.com",
  "password": "Password123@"
}

###

# @name user
GET {{user_base_url}}
Content-Type: application/json

###

# @name updating
PATCH  {{user_base_url}}
Content-Type: application/json

{
  "name": "Ronaldo10"
}

###

# @name delete
DELETE {{user_base_url}}
Content-Type: application/json

###

# @name GetProfile
GET {{profile_base_url}}
Content-Type: application/json

###

# @name SaveProfile
PATCH  {{profile_base_url}}
Content-Type: application/json

{
  "fixedCosts": 100,
  "daysOfWorking": 5,
  "salesPerDay": 20
}

###

# Salvar o id da receita para buscar posteriormente.
# Antes de salvar verificar se ja existe uma receita existente.
# @name create-recipe
POST {{recipes_base_url}}
Content-Type: application/json

{
	"title": "receita",
  "describe": "describre"
}

###

# @name all-recipes
GET {{recipes_base_url}}/all
Content-Type: application/json

###
# aprimorar essa chamada => procurar a receita dentro do user, e não global
# @name unique-recipe-id
GET {{recipes_base_url}}/43
Content-Type: application/json

###

# @name unique-recipe-name
GET {{recipes_base_url}}
Content-Type: application/json

###

# @name updating
PUT {{recipes_base_url}}/43
Content-Type: application/json

{
	"title": "Novo asd",
  "describe": "novo asd"
}

###

# @name delete
DELETE {{recipes_base_url}}/5
Content-Type: application/json

###
# Usar uma variavel em cache ou localStorage para obter o id da receita em questão.
# @name create-ingredient
POST {{ingredients_base_url}}/43
Content-Type: application/json

{
	"name": "ingrediente 4",
	"usedWeight": 2,
	"marketPrice": 10,
	"grossWeight": 4
}

###
# @name unique-ingredient
GET {{ingredients_base_url}}/10
Content-Type: application/json

###

# @name updating-ingredient
PUT {{ingredients_base_url}}/45
Content-Type: application/json

{
	"usedWeight": 10,
	"marketPrice": 50,
	"grossWeight": 100,
  "recipeId": 43
}

###

# @name delete
DELETE {{ingredients_base_url}}/45
Content-Type: application/json